name: build-push

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  ##
  ## Caddy
  ##
  caddy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta_caddy
        with:
          images: waltlenu/caddy
          tag-sha: true
          tag-latest: true
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./caddy
          file: ./caddy/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_caddy.outputs.tags }}
          labels: ${{ steps.docker_meta_caddy.outputs.labels }}

  ##
  ## Synchronet BBS
  ##
  sbbs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta_sbbs
        with:
          images: waltlenu/sbbs
          tag-sha: true
          tag-latest: true
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./sbbs
          file: ./sbbs/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_sbbs.outputs.tags }}
          labels: ${{ steps.docker_meta_sbbs.outputs.labels }}
